name: CopperCX
favicon: null
layout_spectrum: 0.8854825617745519
typography_spectrum: 0.31299046287313104
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.48175343475304544
  lightness: 0.11394948814995587
  saturation: 0.11204155324958265
  rhythmicContrast: 0.15650458890013397
purpose: []
